version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      # - POSTGRES_DATABASE=online-multiplayer
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data # where data is stored
  pg-admin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=your@email.com
      - PGADMIN_DEFAULT_PASSWORD=changeit
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

volumes:
  data:
